### ISSUE TITLE
Cannot use Cloud Datastore Java APIs with Graal VM.

### ISSUE THREAD

**Issue by ludoch** [googleapis/java-datastore#20]
Playing with the native example of Quarkus IO https://quarkus.io/  located at:

https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started

Adding a dep with 
```
       <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-datastore</artifactId>
      <version>1.62.0</version>
    </dependency>
```
And using the Cloud Datastore API (simple imports/usage)

Notice I do not define GAE App Engine APIs which I do not want to use (it would not work anyway in a Java11 titanium pure runtime.

I then compile with:

mvn install -Dnative-image.docker-build -Pnative
...
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.google.protobuf.UnsafeUtil. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.google.protobuf.UnsafeUtil. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
[quarkus-quickstart-runner:6]     analysis:  22,469.29 ms
Printing call tree to /project/reports/call_tree_quarkus-quickstart-runner_20190312_181219.txt
Printing list of used classes to /project/reports/used_classes_quarkus-quickstart-runner_20190312_181222.txt
Printing list of used packages to /project/reports/used_packages_quarkus-quickstart-runner_20190312_181222.txt
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: com.google.appengine.api.urlfetch.HTTPMethod. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: com.google.appengine.api.urlfetch.HTTPMethod. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing com.google.api.client.extensions.appengine.http.UrlFetchTransport.buildRequest(UrlFetchTransport.java:116)
Call path from entry point to com.google.api.client.extensions.appengine.http.UrlFetchTransport.buildRequest(String, String): 
        at com.google.api.client.extensions.appengine.http.UrlFetchTransport.buildRequest(UrlFetchTransport.java:113)
        at com.google.api.client.extensions.appengine.http.UrlFetchTransport.buildRequest(UrlFetchTransport.java:50)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:901)
        at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:183)
        at com.google.datastore.v1.client.Datastore.commit(Datastore.java:87)
        at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:152)
        at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:496)
        at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:493)
        at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
        at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
        at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
        at com.google.cloud.datastore.DatastoreImpl.runQuery(DatastoreImpl.java:176)
        at com.google.cloud.datastore.QueryResultsImpl.sendRequest(QueryResultsImpl.java:72)
        at com.google.cloud.datastore.QueryResultsImpl.computeNext(QueryResultsImpl.java:93)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at java.util.AbstractCollection.containsAll(AbstractCollection.java:317)
        at java.util.RegularEnumSet.containsAll(RegularEnumSet.java:199)
        at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:158)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:131)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

**Comment by lmassaoy** [comment]
Hi @ludoch ! I'm facing the same issue you did (but with translation API). Would you mind sharing with me the way you found to handle this problem? Thank you!

**Comment by manodupont** [comment]
Any answers to that by now ? 

Thanks

**Comment by ludoch** [comment]
Work is happening in [GCP GraalVM project](https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support).
So far, I see pubsub, logging, trace, storage (see samples).
You may ask for status on Datastore on this project.

**Comment by kenyee** [comment]
> Work is happening in [GCP GraalVM project](https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support).
> So far, I see pubsub, logging, trace, storage (see samples).
> You may ask for status on Datastore on this project.

Added a feature request to the issues in that project.  Probably can close this ticket since the GraalVM bug blocking this appears to have been fixed.

**Comment by meredithslota** [comment]
Datastore appears to be supported, see https://github.com/GoogleCloudPlatform/native-image-support-java/tree/master/native-image-samples/native-image-samples-client-library/datastore-sample
