### ISSUE TITLE
LocalHost Check For Emulator URL Throws Exception, Causes Invalidation and Connection Failure

### ISSUE THREAD

**Issue by patrickjp93** [googleapis/java-datastore#570]
#### Environment details

1. Client Library: google-cloud-datastore 2.1.3
2. OS type and version: Mac OS Big Sur 11.6
3. Java version: 1.8.0_301
4. datastore version(s): 2.1.3
5. Emulator Version: latest at time of posting

#### Steps to reproduce

  1. Default emulator start --host=::1 --port=8658
  2. $(gcloud beta emulators datastore env-init)
  3. in Java: DatastoreOptions.getDefaultInstance().getService();

#### Code example

```java
HttpDatastoreRpc.class

private static boolean isLocalHost(String host) { // "::1:8658"
    if(!host.isEmpty() {
        try {
            String normalizedHost = "http://" + removeScheme(host);
            InetAddress hostAddr = InetAddress.getByName(new URL(normalizedHost )).getHost()); //throws Exception
            return hostAddr.isAnyLocalAddress() || hostAddr.isLoopbackAddress();
        } catch (Exception var3) {
        }
    }

    return false;
}
```

#### Stack trace
```
java.lang.IllegalArgumentException: Project endpoint: "::1:8658/v1/projects/my-project" must include scheme.
```

**Comment by meredithslota** [comment]
@aristide-n I think you recently worked on some emulator features - can you PTAL?

**Comment by jainsahab** [comment]
Hi @patrickjp93 , 
Thanks for reporting this issue.

After following the steps you mentioned to reproduce this bug in the latest version,  I also got a failure message.

I tried the following steps
- `gcloud beta emulators datastore start --host-port=[::1]:8658`
-  Reloaded the env variables from `gcloud beta emulators datastore env-init` as following
```
export DATASTORE_DATASET=my-project
export DATASTORE_EMULATOR_HOST=::1:8658
export DATASTORE_EMULATOR_HOST_PATH=::1:8658/datastore
export DATASTORE_HOST=http://::1:8658
export DATASTORE_PROJECT_ID=my-project
```
-  And finally, initialized the service using `DatastoreOptions.getDefaultInstance().getService();`

**OUTPUT**

```
java.net.MalformedURLException: For input string: ":1:8658"
	at java.net.URL.<init>(URL.java:645)
	at java.net.URL.<init>(URL.java:508)
	at java.net.URL.<init>(URL.java:457)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.isLocalHost(HttpDatastoreRpc.java:104)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.<init>(HttpDatastoreRpc.java:62)
	at com.google.cloud.datastore.DatastoreOptions$DefaultDatastoreRpcFactory.create(DatastoreOptions.java:60)
	at com.google.cloud.datastore.DatastoreOptions$DefaultDatastoreRpcFactory.create(DatastoreOptions.java:54)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:564)
	at com.google.cloud.datastore.DatastoreOptions.getDatastoreRpcV1(DatastoreOptions.java:169)
	at com.google.cloud.datastore.DatastoreImpl.<init>(DatastoreImpl.java:68)
	at com.google.cloud.datastore.DatastoreOptions$DefaultDatastoreFactory.create(DatastoreOptions.java:50)
	at com.google.cloud.datastore.DatastoreOptions$DefaultDatastoreFactory.create(DatastoreOptions.java:44)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:544)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.main(HttpDatastoreRpc.java:114)
Caused by: java.lang.NumberFormatException: For input string: ":1:8658"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:222)
	at java.net.URL.<init>(URL.java:640)
	... 13 more
Exception in thread "main" java.lang.IllegalArgumentException: Project endpoint "::1:8658/v1/projects/my-project" must include scheme.
	at com.google.datastore.v1.client.DatastoreOptions$Builder.projectEndpoint(DatastoreOptions.java:146)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.<init>(HttpDatastoreRpc.java:76)
	at com.google.cloud.datastore.DatastoreOptions$DefaultDatastoreRpcFactory.create(DatastoreOptions.java:60)
	at com.google.cloud.datastore.DatastoreOptions$DefaultDatastoreRpcFactory.create(DatastoreOptions.java:54)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:564)
	at com.google.cloud.datastore.DatastoreOptions.getDatastoreRpcV1(DatastoreOptions.java:169)
	at com.google.cloud.datastore.DatastoreImpl.<init>(DatastoreImpl.java:68)
	at com.google.cloud.datastore.DatastoreOptions$DefaultDatastoreFactory.create(DatastoreOptions.java:50)
	at com.google.cloud.datastore.DatastoreOptions$DefaultDatastoreFactory.create(DatastoreOptions.java:44)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:544)
```

Looking closely at the nested exception there is `java.net.MalformedURLException: For input string: ":1:8658"`, it didn't recognize the Ipv6 address and failed, 


**Solution**
In order to use library with IPv6 address, it has to be enclosed within square brackets. ex: `[::1]:4568`, this is the same format that we use while [starting the datastore emulator with IPv6](https://cloud.google.com/sdk/gcloud/reference/beta/emulators/datastore/start#--host-port) (as i did above). Also refer to [rfc 2732, section 2](https://www.ietf.org/rfc/rfc2732.txt) and [java.net.URL documentation](https://docs.oracle.com/javase/10/docs/api/java/net/URL.html#%3Cinit%3E(java.lang.String,java.lang.String,int,java.lang.String)) for more details.
The problem lies with the output of env-init command `gcloud beta emulators datastore env-init`. It should've returned the details with brackets enclosing the host. I'll create a separate ticket to address the problem in the emulator code.

**Comment by jainsahab** [comment]
@patrickjp93 closing this issue for now as library doesn't need a code change, feel free to reopen if you have any questions on this.
